### ISSUE TITLE
Renaming APIs

### ISSUE THREAD

**Issue by thetutlage** [macieklad/adonisjsx#1]
Hey, the package looks great. Thanks for creating it.

I was wondering, if you will be interesting in renaming `jsx` and `streamJsx` to a single object with `render` and `stream` methods.

```ts
interface HttpContext {
  jsx: {
    render: renderFn
    stream: streamFn
  }
}
```

The usage will look as follows

```ts
router.get('/', ({ jsx }) => {
  return jsx.render(Component)
})

router.get('/', ({ jsx }) => {
  return jsx.stream(Component)
})
```

**Comment by macieklad** [comment]
This is now a part of `0.4.0`. Thanks for your suggestions ;)
